[package]
name = "nesRS"
version = "0.1.0"
authors = ["tompko <tompko@gmail.com>"]

[dependencies]
clap = "2"
byteorder = "0.5"
enum_primitive = "0.1"
num = "0.1"
rand = "0.3"
sdl2 = "0.14"
time = "0.1"
